### ISSUE TITLE
Ignition in Apple Home not sending signal.

### ISSUE THREAD

**Issue by tfyb** [athal7/homebridge-hyundai-bluelink#16]
**Describe The Bug:**
When attempting to start the car from the Home app, it receives no response, and nothing even shows up in the log. Unlock and lock are working.

**To Reproduce:**
Attempt to start car in home app.

**Expected behavior:**
Car Starts.

**Logs:**

```
Homebridge logs:
[27/04/2021, 18:54:58] [Hyundai] Vehicle is Locked
[27/04/2021, 18:54:58] [Hyundai] new range 302
[27/04/2021, 18:54:58] [Hyundai] maxRange is 302
[27/04/2021, 18:54:58] [Hyundai] Vehicle is Off
[27/04/2021, 18:56:59] [Hyundai] Unlocking Vehicle
[27/04/2021, 18:57:05] [Hyundai] Unlock Response Unlock successful
[27/04/2021, 18:58:01] [Hyundai] Vehicle is Unlocked
[27/04/2021, 18:58:06] [Hyundai] Locking Vehicle
[27/04/2021, 18:58:06] [Hyundai] Lock Response Lock successful
[27/04/2021, 18:59:01] [Hyundai] Vehicle is Locked

**Plugin Config:**

```json
{
    "credentials": {
        "username": "removed",
        "password": "removed",
        "region": "US",
        "brand": "hyundai",
        "pin": "removed"
    },
    "vehicles": [
        {
            "vin": "removed",
            "maxRange": removed
        }
    ],
    "remoteStart": {
        "cool": false,
        "heat": true,
        "defrost": false,
        "temperature": 73,
        "igniOnDuration": 10
    },
    "platform": "Hyundai"
}

**Screenshots:**
N/A

**Environment:**

* **Plugin Version**: v1.3.3
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.16.1
* **NPM Version**: v7.11.1
* **Operating System**: Raspbian

**Comment by athal7** [comment]
I think I see the problem: https://github.com/athal7/homebridge-hyundai-bluelink/blob/main/src/services/ignition.ts#L43. Will work on a fix.

**Comment by athal7** [comment]
Oh wait that's not the relevant logic 🤔. @tfyb can you turn on debug logging and let me know what you see? Should be some logs about `isOn` and `shouldTurnOn`

**Comment by tfyb** [comment]
```
[28/04/2021, 21:54:19] [Hyundai] Vehicle is Locked
[28/04/2021, 21:54:19] [Hyundai] new range 28
[28/04/2021, 21:54:19] [Hyundai] maxRange is 28
[28/04/2021, 21:54:19] [Hyundai] Vehicle is Off
[28/04/2021, 21:55:20] [Hyundai] Received status update {
  chassis: {
    hoodOpen: false,
    trunkOpen: false,
    locked: true,
    openDoors: {
      frontRight: false,
      frontLeft: false,
      backLeft: false,
      backRight: false
    },
    tirePressureWarningLamp: {
      rearLeft: false,
      frontLeft: false,
      frontRight: false,
      rearRight: false,
      all: false
    }
  },
  climate: {
    active: false,
    steeringwheelHeat: false,
    sideMirrorHeat: false,
    rearWindowHeat: false,
    defrost: false,
    temperatureSetpoint: '75',
    temperatureUnit: 1
  },
  engine: {
    ignition: false,
    accessory: false,
    range: 28,
    charging: undefined,
    batteryCharge12v: 84,
    batteryChargeHV: undefined
  },
  lastupdate: 2021-04-29T01:48:17.000Z
}
[28/04/2021, 21:57:00] [Hyundai] isOn false
[28/04/2021, 21:57:00] [Hyundai] shouldTurnOn false
```

**Comment by athal7** [comment]
Are these the logs after you attempted to start the vehicle?

**Comment by tfyb** [comment]
Yes.

**Comment by athal7** [comment]
Got it, thanks. Will work on a fix

**Comment by athal7** [comment]
Should be fixed in 1.3.4

**Comment by tfyb** [comment]
Great, really appreciate your time an effort! Now the commands are showing up in the log. Unfortunately seems to still not start the car.

```
[30/04/2021, 12:22:04] [Hyundai] Vehicle is Locked
[30/04/2021, 12:22:04] [Hyundai] new range 254
[30/04/2021, 12:22:04] [Hyundai] Vehicle is Off
[30/04/2021, 12:27:13] [Hyundai] Starting Vehicle
[30/04/2021, 12:27:44] [Hyundai] Start Response Failed to start vehicle
```

**Comment by athal7** [comment]
Oh weird, maybe a bluelinky issue at this point 🤔

**Comment by yonigold1** [comment]
Im also having an issue starting the ignition from the home app it doesn't seem to be working for me either. Is there any fix yet?

**Comment by yonigold1** [comment]
Hey @athal7 I'm not sure whose end the issue is on however from my debugging skills i have realized that the command to start the ignition IS in fact going through however it seems like the command that's being sent is incorrect as the BlueLink app DOES in fact register that there is a command being sent however the command seems to have no action. When I try to toggle the Ignition from HomeKit if i go to the BlueLink app and trying to execute any remote action it says "We are currently processing an earlier inquiry for your vehicle please wait 90 seconds..." So it received the ignition start command its just failing. I hope this helps :)

**Comment by athal7** [comment]
Thanks @yonigold1 for the debugging! This project is just calling the start command on the bluelinky library, so if there's an issue with translating to the correct API call, it would have to be in the bluelinky codebase

**Comment by yonigold1** [comment]
There is an [issue](https://github.com/Hacksore/bluelinky/issues/145) that is on Bluelinky's github and I feel that there is progress being made i thought i would attach it here in case anyone wanted to follow

**Comment by james5294** [comment]
i am having this same issue.. any fix?
